services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: argus
      POSTGRES_USER: baseuser
      POSTGRES_PASSWORD: basepassword
    ports:
      - "5434:5432"  # Проксирую на другой порт, чтобы не конфликтовал с локальным сервером
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./microservices/management-handler/internal/db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - net

  gateway:
    build:
      dockerfile: deploy/golang/Dockerfile
      context: .
      args:
        - BUILD_IMAGE=go-build
        - SERVICE_NAME=gateway
    ports:
      - "8080:8080"
    depends_on:
      - broker
      - management-service
    networks:
      - net

  management-service:
    build:
      dockerfile: deploy/golang/Dockerfile
      context: .
      args:
        - BUILD_IMAGE=go-build
        - SERVICE_NAME=management-service
    depends_on:
      - db
      - broker
      - centrifugo
    networks:
      - net

  broker:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - net

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v5
    volumes:
      - ./deploy/centrifugo-config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - "8000:8000"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  yolo:
    build:
      dockerfile: Dockerfile
      context: ./YOLO
    depends_on:
      - db
      - broker
      - management-service
    environment:
      - cfg=deploy_config.json
    networks:
      - net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

networks:
  net:
    driver: bridge